"""OTSC1 current-only structural compounder snapshot; never reads returns."""
from pathlib import Path
import hashlib,json,sys
import numpy as np,pandas as pd
R=Path(__file__).resolve().parents[1];O=R/'research_k/otsc1_structural_compounder_model';O.mkdir(exist_ok=True);F=R/'validated/fundamentals/fundamentals_r12_validated.json'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def dump(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def ratio(a,b):return a/b if pd.notna(a) and pd.notna(b) and b!=0 else np.nan
def pq(df,n):df.to_csv(O/(n+'.csv'),index=False);(O/(n+'.parquet.NOT_CREATED')).write_text('CSV is authoritative; parquet engine unavailable.\n')
def main():
 f=pd.DataFrame(json.loads(F.read_text()));f.report_date=pd.to_datetime(f.report_date);cur=f.sort_values(['kod','report_date']).groupby('kod',as_index=False).tail(1).copy();prev=f.sort_values(['kod','report_date']).groupby('kod').nth(-2).reset_index().set_index('kod')
 cur['revenue_growth']=[ratio(r.revenues-prev.loc[r.kod,'revenues'],abs(prev.loc[r.kod,'revenues'])) if r.kod in prev.index else np.nan for _,r in cur.iterrows()];cur['op_margin']=cur.apply(lambda r:ratio(r.operating_Income,r.revenues),axis=1);cur['cfo_margin']=cur.apply(lambda r:ratio(r.cash_Flow_From_Operating_Activities,r.revenues),axis=1);cur['equity_ratio']=cur.apply(lambda r:ratio(r.total_Equity,r.total_Assets),axis=1);cur['current_ratio']=cur.apply(lambda r:ratio(r.current_Assets,r.current_Liabilities),axis=1);cur['fcf_margin']=cur.apply(lambda r:ratio(r.free_Cash_Flow,r.revenues),axis=1);cur['margin_change']=[r.op_margin-ratio(prev.loc[r.kod,'operating_Income'],prev.loc[r.kod,'revenues']) if r.kod in prev.index else np.nan for _,r in cur.iterrows()];cur['share_change']=[ratio(r.number_Of_Shares-prev.loc[r.kod,'number_Of_Shares'],abs(prev.loc[r.kod,'number_Of_Shares'])) if r.kod in prev.index else np.nan for _,r in cur.iterrows()]
 # Hard-data trajectory is deliberately a separate, transparent input—not an LLM quality claim.
 cur['financial_trajectory']=100*(.30*cur.revenue_growth.rank(pct=True).fillna(.5)+.25*cur.margin_change.rank(pct=True).fillna(.5)+.20*cur.cfo_margin.rank(pct=True).fillna(.5)+.15*cur.equity_ratio.rank(pct=True).fillna(.5)+.10*(-cur.share_change).rank(pct=True).fillna(.5))
 def stage(r):
  if pd.isna(r.revenues) or pd.isna(r.op_margin):return 'UNCLASSIFIED'
  if r.op_margin>=.10 and r.revenue_growth>=.10:return 'ESTABLISHED_ACCELERATOR'
  if r.op_margin>=.05:return 'MATURE_COMPOUNDER'
  if r.revenue_growth>=.15 and r.margin_change>=0:return 'SCALING'
  if r.revenue_growth>=.10:return 'COMMERCIAL_INFLECTION'
  return 'UNCLASSIFIED'
 cur['OTSC1_STAGE']=cur.apply(stage,axis=1);cur['BUSINESS_MODEL_TYPE']='OTHER_UNKNOWN_NO_CURRENT_SOURCE_EVIDENCE';cur['STRUCTURAL_QUALITY']=np.nan;cur['COMMERCIAL_PROOF']=np.nan;cur['MANAGEMENT_EXECUTION']=np.nan;cur['OTSC1_QUALITY']=np.nan;cur['OTSC1_OPPORTUNITY']=np.nan;cur['OTSC1_RISK']=np.nan;cur['confidence']=np.where(cur.financial_trajectory.notna(),.30,.0);cur['hard_data_coverage']=cur[['revenue_growth','op_margin','cfo_margin','equity_ratio','current_ratio','fcf_margin','margin_change','share_change']].notna().mean(axis=1);cur['qualitative_evidence_coverage']=0.;cur['analysis_date']='2026-08-24';cur['source_ids']='validated/fundamentals/fundamentals_r12_validated.json';cur['publication_dates']=cur.report_date.dt.strftime('%Y-%m-%d');cur['evidence_status']='QUALITATIVE_EVIDENCE_UNKNOWN_NO_CURRENT_DOCUMENT_CORPUS'
 stage_spec={'EARLY_VALIDATION':'product/pilots/regulatory validation; not inferred from hard data alone','COMMERCIAL_INFLECTION':'commercial conversion begins; hard-data provisional routing only','SCALING':'growing revenue with improving margins/operating leverage','ESTABLISHED_ACCELERATOR':'established business with acceleration','MATURE_COMPOUNDER':'established profitability/cash generation','UNCLASSIFIED':'insufficient evidence'};dump(O/'OTSC1_STAGE_SPEC.json',stage_spec)
 routing={'policy':'Business model is not inferred without current primary-document evidence. All current rows route to OTHER_UNKNOWN until a sourced RAG corpus is available.','allowed_types':['SOFTWARE_SAAS','SEMICONDUCTOR_COMPONENT','AUTOMOTIVE_DESIGN_WIN','MEDTECH_INSTALLED_BASE_CONSUMABLE','PHARMA_MEDTECH_ADOPTION','INDUSTRIAL_EQUIPMENT','DEFENCE_LONG_CYCLE','CONSUMER_BRAND','SERVICE','OTHER']};dump(O/'OTSC1_BUSINESS_MODEL_ROUTING.json',routing)
 schema={'type':'object','required':['ticker','analysis_date','stage','business_model_type','otsc1_quality','otsc1_opportunity','otsc1_risk','confidence','source_ids','publication_dates'],'properties':{'ticker':{'type':'string'},'stage':{'enum':list(stage_spec)},'evidence_for':{'type':'array'},'evidence_against':{'type':'array'},'confidence':{'type':'number'}}};dump(O/'OTSC1_JSON_SCHEMA.json',schema)
 (O/'OTSC1_LLM_PROMPT.md').write_text('# OTSC1 evidence-engine prompt\n\nUse only supplied dated passages. For every claim output claim, evidence_for, evidence_against, source_ids, publication_dates, confidence and score; use UNKNOWN where evidence is absent. Never invent financial metrics or citations.\n')
 (O/'OTSC1_SOURCE_POLICY.md').write_text('# OTSC1 source policy\n\nPriority: annual/quarterly reports, regulatory releases, official presentations, MFN releases. Current workspace contains no usable current document corpus, so no LLM qualitative assertion is permitted in this snapshot.\n')
 (O/'OTSC1_MODEL_SPEC.md').write_text('# OTSC1 structural compounder model\n\nQuality design weights: Structural Quality 30%, Commercial Proof 25%, Financial Trajectory 25%, Management Execution 20%. Opportunity is separate (expectation gap 50%, rerating trigger 30%, underappreciation 20%); risk is separate. Market cap never defines quality. This current snapshot has only Financial Trajectory hard data; all qualitative dimensions remain UNKNOWN pending source-grounded RAG.\n')
 pq(cur[['kod','analysis_date','OTSC1_STAGE','BUSINESS_MODEL_TYPE','OTSC1_QUALITY','STRUCTURAL_QUALITY','COMMERCIAL_PROOF','financial_trajectory','MANAGEMENT_EXECUTION','OTSC1_OPPORTUNITY','OTSC1_RISK','confidence','hard_data_coverage','qualitative_evidence_coverage','source_ids','publication_dates','evidence_status']],'OTSC1_CURRENT_SCORES')
 ev=cur[['kod','analysis_date','source_ids','publication_dates','evidence_status']].copy();ev['claim']='UNKNOWN';ev['evidence_for']='[]';ev['evidence_against']='[]';pq(ev,'OTSC1_CURRENT_EVIDENCE');pq(pd.DataFrame(columns=['ticker','kpi','value','source_id','publication_date','validation_status']),'OTSC1_COMMERCIAL_KPI_EXTRACTIONS');pq(pd.DataFrame(columns=['ticker','original_statement','date','target','later_outcome','result']),'OTSC1_PROMISE_DELIVERY_LEDGER');pq(pd.DataFrame({'ticker':cur.kod,'FINANCING_RISK':'UNKNOWN','DILUTION_RISK':np.where(cur.share_change>.10,'ELEVATED','UNKNOWN'),'CUSTOMER_CONCENTRATION':'UNKNOWN','REGULATORY_RISK':'UNKNOWN','BINARY_OUTCOME_RISK':'UNKNOWN','SINGLE_PRODUCT_RISK':'UNKNOWN','ACCOUNTING_RISK':'UNKNOWN','EXECUTION_RISK':'UNKNOWN','BALANCE_SHEET_RISK':np.where(cur.equity_ratio<.20,'ELEVATED','UNKNOWN'),'VALUATION_RISK':'UNKNOWN'}),'OTSC1_RISK_MAP');pq(pd.DataFrame(columns=['ticker','trigger','expected_timing','evidence','dependencies','confidence']),'OTSC1_RERATING_TRIGGERS')
 known=['SMAR','ACCON','SECARE','PHYS','SENZA','SEDANA','SAAB-B'];kc=[]
 for k in known:
  q=cur[cur.kod==k];kc.append({'ticker':k,'found':not q.empty,'stage':None if q.empty else q.OTSC1_STAGE.iloc[0],'quality':'UNKNOWN_NO_QUALITATIVE_EVIDENCE','opportunity':'UNKNOWN','risk':'PARTIAL_HARD_ONLY','scaling_mechanism':'UNKNOWN','strongest_evidence':'No current primary-document corpus','strongest_contrary_evidence':'No current primary-document corpus','thesis_killers':'UNKNOWN'})
 pd.DataFrame(kc).to_csv(O/'OTSC1_KNOWN_CASE_SANITY.csv',index=False)
 sample=cur.sort_values('kod').dropna(subset=['kod']).head(30);pd.DataFrame({'ticker':sample.kod,'selection_rule':'first 30 lexicographically among current structured records; no return data','size_segment':'UNKNOWN_NO_PIT_MARKET_CAP','sector':'UNKNOWN_NO_CURRENT_SECTOR_INTERVAL','stage':sample.OTSC1_STAGE}).to_csv(O/'OTSC1_BLIND_SANITY_SAMPLE.csv',index=False)
 pd.DataFrame({'size_segment':['UNKNOWN_NO_PIT_MARKET_CAP'],'n':[len(cur)],'quality_correlation_with_size':['NOT_IDENTIFIABLE'],'note':['Market cap not used in score.']}).to_csv(O/'OTSC1_SIZE_NEUTRALITY_AUDIT.csv',index=False);cur.OTSC1_STAGE.value_counts().rename_axis('stage').reset_index(name='n').to_csv(O/'OTSC1_STAGE_AUDIT.csv',index=False);pd.DataFrame({'ticker':cur.kod,'business_model':cur.BUSINESS_MODEL_TYPE,'kpis_selected':'NONE','status':'BAD_KPI_ROUTING_AVOIDED_NO_SOURCE_EVIDENCE'}).to_csv(O/'OTSC1_KPI_ROUTING_AUDIT.csv',index=False);pd.DataFrame([{'claim_count':0,'supported':0,'partially_supported':0,'unsupported':0,'contradicted':0,'status':'WARNING_NO_LLM_CLAIMS_TO_AUDIT'}]).to_csv(O/'OTSC1_LLM_HALLUCINATION_AUDIT.csv',index=False)
 report=['# OTSC1 current snapshot','',f'Analyzed current structured records: {len(cur)}.','', 'The hard-data stage routing is provisional. No current document corpus or legacy OT code was available, so the model correctly emits UNKNOWN rather than an invented commercial, moat, management, opportunity or risk assessment.','', 'Size-neutrality: market cap is not a model input; PIT/current market cap was unavailable for correlation diagnostics.','', 'Forward readiness: FALSE until source-grounded LLM evidence/RAG, management-promise ledger and validation are available.'];(O/'OTSC1_CURRENT_REPORT.md').write_text('\n'.join(report)+'\n')
 freeze={'spec_sha256':sha(O/'OTSC1_MODEL_SPEC.md'),'prompt_sha256':sha(O/'OTSC1_LLM_PROMPT.md'),'routing_sha256':sha(O/'OTSC1_BUSINESS_MODEL_ROUTING.json'),'schema_sha256':sha(O/'OTSC1_JSON_SCHEMA.json'),'source_policy_sha256':sha(O/'OTSC1_SOURCE_POLICY.md'),'implementation_sha256':sha(Path(__file__)),'current_data_sha256':sha(F),'status':'NOT_FROZEN_FORWARD_LLM_EVIDENCE_PIPELINE_MISSING'};dump(O/'OTSC1_CURRENT_PRE_FORWARD_FREEZE.json',freeze)
 out={'OTSC1_BUILD':'PARTIAL','OTSC1_SIZE_NEUTRALITY':'WARNING','OTSC1_STAGE_ROUTING':'WARNING','OTSC1_BUSINESS_MODEL_ROUTING':'WARNING','OTSC1_HARD_DATA_VALIDATION':'PASS','OTSC1_LLM_EVIDENCE_VALIDATION':'WARNING','OTSC1_KNOWN_CASE_SANITY':'WARNING','OTSC1_BLIND_SAMPLE_SANITY':'WARNING','OTSC1_FORWARD_READY':False,'RETURN_DATA_ACCESSED':False,'PRODUCTION_MUTATION_PERFORMED':False,'NEXT_ACTION':'REVIEW_MODEL_STRUCTURE_BEFORE_FREEZE'};dump(O/'OTSC1_BUILD_RESULT.json',out);print(json.dumps(out,indent=2))
if __name__=='__main__':main()
