import hashlib,json
from pathlib import Path
ROOT=Path('/home/hannesb/momentum_v2');OUT=ROOT/'research_k/h0_v3_single_drawdown_policy_audit';OUT.mkdir(exist_ok=True)
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 pre={'study':'H0_V3_SINGLE_DRAWDOWN_POLICY_AUDIT','status':'PREREGISTERED_BEFORE_RESULT','primary_estimand':'H0_V3_DD20_CASH_TO_NEXT_ORDINARY_PORTFOLIO_EFFECT','policy':'DD20_CASH_TO_NEXT_ORDINARY','threshold':-0.20,'threshold_selected_from_old_results':False,'threshold_rationale':'20 percent is a material drawdown convention rather than ordinary short-horizon noise.','one_event_per_episode':True,'execution':'NEXT_TRADING_DAY_ADJUSTED_CLOSE','cash_until':'NEXT_ORDINARY','replacement_security':'NONE','special_reentry_rule':'NONE','parameter_sweep':False,'subgroup_rescue':False,'production_change_authorized':False,'windows':['W1','W2'],'primary_outcome':'net CAGR delta, reported separately by window','decision_rule':'positive both W1 and W2 => DD20_CASH_REPLICATED_POSITIVE; mixed signs => DD20_CASH_MIXED_W1_W2; both nonpositive => DD20_CASH_NO_VALUE'}
 (OUT/'PREREGISTRATION.json').write_text(json.dumps(pre,indent=2)+'\n')
 (OUT/'PREREGISTRATION.md').write_text('# H0 V3 single drawdown policy audit\n\nA new, one-policy test: sell a held position after a 20% adjusted-price drawdown from its running episode peak at next trading-day adjusted close, then hold its sleeve in zero-return cash until the next ordinary H0 V3 panel. DD20 is an ex-ante material-event convention, not selected from historical policy performance. No alternative threshold, replacement arm, subgroup, or production change is authorized.\n')
 (OUT/'LEGACY_CONTEXT.md').write_text('# Legacy context\n\nThe historical corrected drawdown study tested DD10/DD20/DD30/DD40 × CASH/NEXT_RANKED and selected no arm. This DD20-CASH study is therefore a new policy audit, not a replay or revalidation. No old arm result was used to select the threshold or cash handling.\n')
 freeze={'prereg_sha256':sha(OUT/'PREREGISTRATION.json'),'prereg_markdown_sha256':sha(OUT/'PREREGISTRATION.md'),'policy':'DD20_CASH_TO_NEXT_ORDINARY','threshold':-0.20,'threshold_selected_from_old_results':False,'one_event_per_episode':True,'execution':'NEXT_TRADING_DAY_ADJUSTED_CLOSE','cash_until':'NEXT_ORDINARY','replacement_security':'NONE','special_reentry_rule':'NONE','parameter_sweep':False,'subgroup_rescue':False,'production_change_authorized':False,'frozen_h0_source_sha256':sha(ROOT/'tools/h0_v3_kor.py'),'adapter_sha256':sha(ROOT/'tools/frozen_h0_v3_policy_adapter.py')}
 (OUT/'PLAN_FREEZE.json').write_text(json.dumps(freeze,indent=2)+'\n')
if __name__=='__main__':main()
