import csv,hashlib,json
from pathlib import Path
V=Path('/home/hannesb/momentum_v2');O=V/'research_k/h0_v3_architecture_revalidation_gate';P0=O/'P0_FIRST_RERUN';O.mkdir(exist_ok=True);P0.mkdir(exist_ok=True)
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 matrix=V/'research_k/h0_v3_architecture_compatibility_audit/ARCHITECTURE_COMPATIBILITY_MATRIX.csv';cand=V/'research_k/h0_v3_architecture_compatibility_audit/ARCHITECTURE_REVALIDATION_CANDIDATES.csv';impact=V/'research_k/h0_v3_architecture_compatibility_audit/CANONICAL_STATUS_IMPACT.csv'
 expect={'matrix':'86197e96f90ee1631ec3a9806ba85494f3bf7a19ebae904a16c41bee1a873510','candidate':'11a8e683e1d6abf9abc26a47822bcf6811ed9d0733fa0c2fa1692485ec4f8bdf'}
 if sha(matrix)!=expect['matrix'] or sha(cand)!=expect['candidate']:raise SystemExit('compatibility input hash mismatch')
 adapter=V/'tools/frozen_h0_v3_policy_adapter.py';base_sha=sha(V/'tools/h0_v3_kor.py')
 method='''# H0 V3 architecture revalidation method\n\nEvery rerun is `INTERVENTION_OFF` versus `INTERVENTION_ON` in the shared frozen adapter. Base OFF must reproduce W1/W2 panel net returns, NAV, pre-SMA and final sets, weights, turnover and cost before the intervention is enabled. Only one frozen intervention may differ. No parameter sweep, retraining, subgroup rule or recovery-candidate freeze is permitted.\n'''
 spec=f'''# Frozen policy adapter specification\n\nAdapter: `tools/frozen_h0_v3_policy_adapter.py` SHA-256 `{sha(adapter)}`.\n\nIt preserves the verified frozen ranking, ordinary/intermediate cadence, `selected_pre_SMA`, post-selection SMA, inverse-volatility sizing, clip-then-normalize, set-overlap turnover and 20 bp panel cost. A policy hook may alter one documented action only.\n'''
 contract={'contract':'BASE_ARCHITECTURE_REPRODUCTION_CONTRACT_V1','frozen_h0_source_sha256':base_sha,'windows':['W1','W2'],'required_metrics':['max_abs_panel_net_diff','max_abs_NAV_diff','selected_pre_SMA_set_diff','final_selected_set_diff','target_weight_diff','turnover_diff','cost_diff'],'thresholds':{'max_abs_panel_net_diff':5.1e-7,'set_diff_count':0,'target_weight_diff':1e-12,'turnover_diff':1e-12,'cost_diff':1e-12}}
 (O/'ARCHITECTURE_REVALIDATION_METHOD.md').write_text(method);(O/'FROZEN_POLICY_ADAPTER_SPEC.md').write_text(spec);(O/'BASE_REPRODUCTION_CONTRACT.json').write_text(json.dumps(contract,indent=2)+'\n')
 plans=[
 ['EARLY_EXTERNAL_CASH_TOPUP_EXISTING_WINNER','PORTFOLIO','monthly_cash_early_topup_vs_next_rebalance_audit/RESULT.json','SUPPORTED_POST_LOCK','REPRODUCTION_VERIFIED_FOR_LOCAL_ESTIMAND','hard-cap is intervention-specific; local matched timing uses correct frozen core','NO','NONE','External cash timing to same existing winner; no base-state change','YES','NO','NO','NOT_APPLICABLE','NO','Local BUY-vs-WAIT remains usable; full cash sleeve is a separate cap-semantics policy question.'],
 ['CORRECTED_DRAWDOWN_EXIT','PORTFOLIO','exit_architecture_factorial/results_*.json','CLOSED_CLEAN_NULL','INVALID_BASE_ARCHITECTURE','cadence, SMA, sizing, selected_pre_SMA turnover/cost','YES','P0','Frozen DD threshold and cash/replacement rule only','YES','YES','YES','none','NO','Portfolio exit closure at risk; DD forward diagnostic remains separate.'],
 ['SMA_TRANSITION_PORTFOLIO_EXIT','PORTFOLIO','information_exit/SELECTION_DECISION.json','SEQUENTIAL_GATE_CLOSED','INVALID_BASE_ARCHITECTURE','cadence, retain/refill, SMA, sizing, turnover/cost','YES','P0','Frozen SMA-transition-to-cash policy only','YES','YES','CONDITIONAL','original W1 positive/maximin gate; W2 only if W1 passes','NO','Existing W1 sequential gate must be replayed on frozen base.'],
 ['TOPN_RANK_PORTFOLIO_EXIT_20','PORTFOLIO','information_exit/SELECTION_DECISION.json','SEQUENTIAL_GATE_CLOSED','INVALID_BASE_ARCHITECTURE','cadence, retain/refill, SMA, sizing, turnover/cost','YES','P0','Frozen Top-20 dropout-to-cash policy only','YES','YES','CONDITIONAL','original W1 positive/maximin gate; W2 only if W1 passes','NO','Existing W1 sequential gate must be replayed on frozen base.'],
 ['TOPN_RANK_PORTFOLIO_EXIT_30','PORTFOLIO','information_exit/SELECTION_DECISION.json','SEQUENTIAL_GATE_CLOSED','INVALID_BASE_ARCHITECTURE','cadence, retain/refill, SMA, sizing, turnover/cost','YES','P0','Frozen Top-30 dropout-to-cash policy only','YES','YES','CONDITIONAL','original W1 positive/maximin gate; W2 only if W1 passes','NO','Existing W1 sequential gate must be replayed on frozen base.'],
 ['REENTRY_SCORE_IMPROVEMENT','PORTFOLIO','h0_reentry_score_improvement_results.json','CLOSED_CLEAN_MIXED','INVALID_BASE_ARCHITECTURE','cadence, retain/refill, SMA, sizing, selected_pre_SMA turnover/cost','YES','P0','At ordinary fresh selection, reentry allowed only when score >= prior exit score + 0.10','YES','YES','YES','positive in both windows screen','NO','First replay candidate: no retraining and exact threshold available.'],
 ['TEMPORARY_EXIT_GUARD','PORTFOLIO','h0_temporary_exit_guard_results.json','CLOSED_CLEAN_NEGATIVE','INVALID_BASE_ARCHITECTURE','cadence, retain/refill, SMA, sizing, turnover/cost','YES','P0','Frozen rank 31–45 / SMA / relative-return guard','YES','YES','YES','none','NO','Material old base mismatch.'],
 ['MODELLED_EXIT_GUARD','PORTFOLIO','h0_exit_model_time_split_results.json','CLOSED_CLEAN_NEGATIVE','INVALID_BASE_ARCHITECTURE','cadence, retain/refill, SMA, sizing, turnover/cost','YES','P1','Existing frozen prediction replay within frozen portfolio state','YES','YES','YES','none','YES','Separate retraining/old-prediction availability decision required.'],
 ['MODEL_REPLACEMENT','PORTFOLIO','global_ml_full_pit_race/results.json','CLOSED_CLEAN_MIXED','INVALID_BASE_ARCHITECTURE','equal-weight non-SMA 8W simulator','YES','P1','Replay frozen ML score outputs as ranking replacement in frozen base','YES','YES','YES','none','MAYBE','Portfolio replay before any retraining.'],
 ['H0_POOL_ML_RERANK','SELECTION','cross_model_arch_b/results.json','PENDING_EXISTING_AUDIT','INVALID_BASE_ARCHITECTURE','equal-weight non-SMA 8W simulator','YES','P1','Replay frozen ML score outputs within frozen H0 candidate pool','YES','YES','YES','none','MAYBE','Existing canonical status is already pending; no P0 urgency.'],
 ['ML_CANDIDATE_GENERATION','SELECTION','candidate_generation_architecture/results.json','PARTIALLY_REPLACED','INVALID_BASE_ARCHITECTURE','equal-weight non-SMA 8W simulator','YES','P1','Replay frozen candidate-set outputs in frozen base','YES','YES','YES','none','MAYBE','Source mapping remains partial.'],
 ['DYNAMIC_ROUTING','PORTFOLIO','dynamic_routing_architecture/results.json','CLOSED_NONREPLICATION','INVALID_BASE_ARCHITECTURE','equal-weight non-SMA 8W simulator','YES','P1','Replay frozen routing assignments in frozen base','YES','YES','YES','none','MAYBE','Replay first; no routing retraining within this gate.'],
 ['SIZING_RISK_ARCHITECTURE','RISK','portfolio_layer_fairness/results.json','MIXED','INVALID_BASE_ARCHITECTURE','all portfolio layers custom','YES','P1','Named frozen sizing layer only','YES','YES','YES','none','NO','No single canonical closure; no P0 action.']]
 cols=['canonical_mechanism_id','estimand_level','old_artifact','old_verdict','current_canonical_status','architecture_status','material_mismatches','architecture_rerun_required','priority','intervention_definition','base_reproduction_required','W1_required','W2_required','sequential_gate_if_any','retraining_required','reason']
 plan_rows=[]
 for x in plans:
  current=('PENDING_ARCHITECTURE_REVALIDATION' if x[6]=='YES' else ('SUPPORTED_POST_LOCK' if x[0]=='EARLY_EXTERNAL_CASH_TOPUP_EXISTING_WINNER' else x[3]))
  plan_rows.append([x[0],x[1],x[2],x[3],current,x[4],x[5],x[6],x[7],x[8],x[9],x[10],x[11],x[12],x[13],x[14]])
 with open(O/'H0_V3_ARCHITECTURE_REVALIDATION_PLAN.csv','w',newline='') as f:w=csv.writer(f);w.writerow(cols);w.writerows(plan_rows)
 pre={'study':'H0_V3_ARCHITECTURE_REVALIDATION__REENTRY_SCORE_IMPROVEMENT','status':'PREREGISTERED_BEFORE_RUN','base':'frozen H0 V3 via shared adapter','frozen_h0_source_sha256':base_sha,'windows':['W1','W2'],'intervention':'At ordinary fresh selection, an exited name is allowed only if current score >= its recorded exit score + 0.10; candidates otherwise follow unchanged frozen rank order.','intervention_must_not_change':['signal','PIT eligibility','ordinary/intermediate cadence','SMA order','sizing','clip-normalization','turnover','cost'],'decision_rule':'Both window effects are reported; no production change.','no_parameter_changes':True,'no_subgroup_rescue':True}
 (P0/'PREREGISTRATION.json').write_text(json.dumps(pre,indent=2)+'\n')
 freeze={'study':'P0_ARCHITECTURE_REVALIDATION_FREEZE_V1','compatibility_matrix_sha256':sha(matrix),'candidate_list_sha256':sha(cand),'canonical_impact_sha256':sha(impact),'frozen_h0_source_sha256':base_sha,'adapter_sha256':sha(adapter),'P0_mechanism_ids':[x[0] for x in plans if x[6]=='YES' and x[7]=='P0'],'first_mechanism':'REENTRY_SCORE_IMPROVEMENT','first_rerun_prereg_sha256':sha(P0/'PREREGISTRATION.json'),'windows':['W1','W2'],'cost_rate':.002,'no_parameter_changes':True,'no_subgroup_rescue':True,'recovery_candidate_freeze_created':False}
 (O/'P0_ARCHITECTURE_REVALIDATION_FREEZE.json').write_text(json.dumps(freeze,indent=2)+'\n')
 result={'study':'H0_V3_ARCHITECTURE_REVALIDATION_GATE','compatibility_inputs_verified':True,'candidates_reviewed':len(plans),'false_positives_removed':['EARLY_EXTERNAL_CASH_TOPUP_EXISTING_WINNER (local matched timing estimand)'],'rerun_required':sum(x[6]=='YES' for x in plans),'priority_counts':{p:sum(x[6]=='YES' and x[7]==p for x in plans) for p in ['P0','P1','P2','NONE']},'first_p0':'REENTRY_SCORE_IMPROVEMENT','adapter_sha256':sha(adapter),'p0_freeze_sha256':sha(O/'P0_ARCHITECTURE_REVALIDATION_FREEZE.json'),'no_global_canonical_map_modified':True}
 (O/'GATE_RESULT.json').write_text(json.dumps(result,indent=2)+'\n');(O/'SUMMARY.md').write_text('# H0 V3 architecture revalidation gate\n\nOnly the first frozen P0 revalidation may run after this gate. Early external cash topup is not first: its local matched timing estimand already uses the frozen core; the hard cap belongs to the separate cash-sleeve intervention.\n')
if __name__=='__main__':main()
