import hashlib,json
from pathlib import Path
V=Path('/home/hannesb/momentum_v2');O=V/'research_k/h0_v3_architecture_revalidation_gate/P0_EARLY_TOPUP_REVALIDATION';O.mkdir(exist_ok=True)
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 pre={'study':'EARLY_EXTERNAL_CASH_TOPUP_EXISTING_WINNER_ARCHITECTURE_REVALIDATION','status':'PREREGISTERED_BEFORE_RUN','primary_estimand':'LOCAL_MATCHED_CASH_TIMING_ESTIMAND','secondary_estimand':'FULL_PORTFOLIO_TOPUP_POLICY','cash_contribution_sek':7000,'monthly_observation':'unchanged from locked ARM D','selection':'existing final H0 holding in frozen rank order; same hard incremental 6% nominal-cap/spill intervention semantics','wait_horizon':'next ordinary rebalance','cost_rate':.002,'base':'shared frozen H0 V3 adapter','no_parameter_changes':True,'no_subgroup_rescue':True}
 (O/'PREREGISTRATION.json').write_text(json.dumps(pre,indent=2)+'\n');(O/'PREREGISTRATION.md').write_text('# Early topup architecture revalidation\n\nPrimary: local matched 7,000 SEK early-versus-wait timing to next ordinary rebalance. Secondary: frozen sequential full policy. The historical hard 6% nominal-cap/spill rule is frozen as the intervention, not treated as H0 base sizing.\n')
 freeze={'prereg_sha256':sha(O/'PREREGISTRATION.json'),'frozen_h0_source_sha256':sha(V/'tools/h0_v3_kor.py'),'adapter_sha256':sha(V/'tools/frozen_h0_v3_policy_adapter.py'),'old_result_sha256':sha(V/'research_k/monthly_cash_early_topup_vs_next_rebalance_audit/RESULT.json'),'no_parameter_changes':True,'no_subgroup_rescue':True}
 (O/'PLAN_FREEZE.json').write_text(json.dumps(freeze,indent=2)+'\n')
 (O/'EARLY_TOPUP_ESTIMAND_RESOLUTION.md').write_text('# Estimand resolution\n\n**A — LOCAL_MATCHED_CASH_TIMING_ESTIMAND:** same 7,000 SEK, same frozen selected existing holding(s), same early date and next ordinary meeting; EARLY value minus WAIT value. Architecture dependence: **PARTIAL** because event identity depends on frozen selection/SMA/state, but the matched cash return is not H0 turnover accounting.\n\n**B — FULL_PORTFOLIO_TOPUP_POLICY:** sequential external-cash sleeve versus BASE_WAIT across the complete window. Architecture dependence: **MATERIAL** through state path, final holdings, cash merger and interaction with the old hard-cap/spill intervention.\n\nThe frozen H0 clip-normalization cap is not substituted for the historical 6% cash-sleeve cap: the latter is an explicitly frozen intervention parameter.\n')
if __name__=='__main__':main()
