#!/usr/bin/env python3
from __future__ import annotations
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1];PRE=R/'research_i/LEGACY_V2_COVERAGE_MATRIX_PRE_BATCH3.json';RES=R/'research_i/results/SPARI_BATCH3_FINAL_LEGACY_V1/summary.json';OUT=R/'research_i/LEGACY_V2_COVERAGE_MATRIX.json';DOC=R/'docs/LEGACY_V2_COVERAGE_MATRIX.md'
def main():
 m=json.loads(PRE.read_text());s=json.loads(RES.read_text());batch3={'run_correlation_refill_stage119.py':s['results']['correlation_refill_085'],'run_fundamental_residual_to_roa_current.py':s['results']['roa_profitability_quality']}
 for r in m['rows']:
  if r['legacy_test'] in batch3:r['batch3_result']=batch3[r['legacy_test']];r['final_disposition']='TESTAD PÅ V2 BATCH 3 — '+batch3[r['legacy_test']];r['återstår_ja_nej']='nej';r['var_testad']='Research I Batch 3'
  else:r['batch3_result']=None;r['final_disposition']=r['V2_status']
 counts={'ursprungliga_REPLIKERA_NU':46,'redan_besvarade_DG':1,'batch1':8,'batch2':3,'data_blockerade':14,'definitions_blockerade':4,'duplicerade':14,'faktiskt_kvarvarande_fore_batch3':2,'batch3_tester':2,'kvarvarande_efter_batch3':0,'resultatgranskade_varianter_Research_I':16}
 final={'matrix_id':'LEGACY_V2_COVERAGE_MATRIX_FINAL_AFTER_BATCH3','source_registry_sha256':m['source_registry_sha256'],'source_scripts':420,'rows':m['rows'],'counts':counts,'legacy_results_used_as_evidence':False,'legacy_replication_program_status':'STOPPED_COMPLETE_NO_BATCH4','new_forward_challengers_from_batch3':[],'future_research_policy':'New ideas must be registered as new research, not legacy replication.'};OUT.write_text(json.dumps(final,ensure_ascii=False,sort_keys=True,indent=2)+'\n')
 lines=['# LEGACY_V2_COVERAGE_MATRIX — slutlig 46/46','',f"Legacyprogrammet är **STOPPAT och komplett**. Batch 3 gav inget stöd för ROA eller korrelationsrefill och skapade ingen ny forward-challenger.",'','## Summering','', '| Mått | Antal |','|---|---:|']+[f"| {k} | {v} |" for k,v in counts.items()]+['','## Exakt differens för alla 46','','| # | legacy_test | ekonomisk_hypotes | familj | V2_status | var_testad | resultat | återstår | orsak |','|---:|---|---|---|---|---|---|---|---|']
 for i,r in enumerate(final['rows'],1):
  esc=lambda x:str(x or '—').replace('|','/').replace('\n',' ')
  result=r['final_disposition'] if r.get('batch3_result') else r['resultat'];lines.append(f"| {i} | `{esc(r['legacy_test'])}` | {esc(r['ekonomisk_hypotes'])} | {esc(r['familj'])} | {esc(r['V2_status'])} | {esc(r['var_testad'])} | {esc(result)} | {esc(r['återstår_ja_nej'])} | {esc(r['orsak'])} |")
 lines += ['','## Batch 3','','### ROA / profitability quality — INGET STÖD','','På exakt ROA-täckningsmatchad population föll mean IC från 0,1525 till 0,1365 (Δ −0,0160), median IC Δ −0,0336 och Top-30 IC Δ −0,0986. Challenger-CAGR var 15,86 % mot 27,01 % för täckningsmatchad H0. Populationen hade 8 584 rader, 340 instrument och **0 terminalinstrument med ROA**. Resultatet är både negativt och kraftigt survivorshipbegränsat.','','### Correlation refill 0,85 — INGET STÖD','','Regeln var testbar men band inte under OOS: inga Top-30-kandidater överskred 0,85 mot redan valda namn. Rankings, holdings och samtliga portföljmått blev därför identiska med H0. Ingen närliggande tröskel testades.','','## Fortsatt blockerad data','','Report/attention/PEAD, dividend-gap och insider-gap är otestade på grund av saknad QA-godkänd PIT-eventdata. ATR/high-low är fortsatt blockerad. Detta är inte negativa resultat.','','## Avslut','','Varje av de 46 relevanta `REPLIKERA NU`-posterna är nu testad, täckt av ett annat V2-test, blockerad av data/definition eller bedömd som ekonomisk dubblett. Ingen Batch 4 skapas. Framtida idéer ska separeras som **NY FORSKNING**. H0/H1/H2 fortsätter oförändrade.']
 DOC.write_text('\n'.join(lines)+'\n');print(json.dumps({'rows':len(final['rows']),'counts':counts,'json':str(OUT),'markdown':str(DOC)},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
