#!/usr/bin/env python3
"""K2A data-only forensic audit. Deliberately never imports/reads target or portfolio code."""
from pathlib import Path
from collections import Counter
import hashlib,json,math,datetime,statistics
R=Path(__file__).resolve().parents[1];O=R/'research_k/k2a_marketcap_ev_audit_v1'
FILES=[R/'validated/fundamentals/fundamentals_r12_validated.json',R/'panels/core_fundamenta_panel.json',R/'panels/core_panel.json',R/'validated/prices/prices_validated.json',R/'validated/terminal_events.json',R/'docs/probes/swagger_v1.json',R/'docs/probes/fund_split_verify.json',R/'validated/manifest_sparA.json',R/'validated/manifest_sparB.json',R/'validated/manifest_sparC.json']
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def q(a,p):
 a=sorted(a);return a[min(len(a)-1,int((len(a)-1)*p))] if a else None
def main():
 assert not O.exists();r12=json.load(open(FILES[0]));panel=json.load(open(FILES[1]));term=set(json.load(open(FILES[4])));split=json.load(open(FILES[6]))
 errs=[]
 for r in r12:
  p,n,e=r.get('profit_To_Equity_Holders'),r.get('number_Of_Shares'),r.get('earnings_Per_Share')
  if p is not None and n and e is not None and abs(p/n)>1e-12:errs.append(abs(e-p/n)/abs(p/n))
 semantics={'field':'number_Of_Shares','documented_schema':'OpenAPI numeric field only; no outstanding/weighted-average/period-end/basic/diluted/effective-date semantics','unit_inference':'million shares, because report totals are MSEK and profit_To_Equity_Holders / number_Of_Shares reproduces EPS','eps_identity':{'n':len(errs),'median_relative_error':statistics.median(errs),'p95_relative_error':q(errs,.95),'within_1pct':sum(x<=.01 for x in errs)/len(errs),'within_10pct':sum(x<=.10 for x in errs)/len(errs)},'split_evidence':split,'forensic_conclusion':'REPORT_PERIOD_EPS_DENOMINATOR_OR_CLOSE_PROXY; NOT VERIFIED PERIOD-END SHARES OUTSTANDING','market_known_time':'report_date is defensible availability date; report_end_date is economic period end and forbidden as availability date','staleness_rule_if_future_use':'latest report_date <= panel_date; no interpolation; staleness retained explicitly','corporate_actions':'No complete effective-date chain for issuance, repurchase, cancellation and split basis','multiple_share_classes':'No general company-total equity value can be formed from total-company report shares times one listed class price; class aggregation needs class-level outstanding shares and prices.'}
 dump(O/'number_of_shares_forensic_qa.json',semantics)
 cov={}
 for y,g in __import__('itertools').groupby(sorted(panel,key=lambda x:x['panel_date'][:4]),key=lambda x:x['panel_date'][:4]):
  z=list(g);withf=[x for x in z if x.get('has_fundamenta')];cov[y]={'panel_rows':len(z),'fundamental_rows':len(withf),'fundamental_coverage':len(withf)/len(z),'instruments':len({x['kod'] for x in z}),'fundamental_instruments':len({x['kod'] for x in withf}),'terminal_rows':sum(x['kod'] in term for x in z),'terminal_rows_with_fundamenta':sum(x['kod'] in term and x.get('has_fundamenta') for x in z)}
 lags=[x['fundamenta_days_since'] for x in panel if x.get('has_fundamenta') and x.get('fundamenta_days_since') is not None]
 coverage={'overall':{'panel_rows':len(panel),'rows_with_fundamenta':sum(x.get('has_fundamenta') for x in panel),'instruments':len({x['kod'] for x in panel}),'instruments_with_fundamenta':len({x['kod'] for x in panel if x.get('has_fundamenta')}),'terminal_instruments':len(term),'terminal_instruments_with_fundamenta':len({x['kod'] for x in panel if x['kod'] in term and x.get('has_fundamenta')}),'staleness_days':{'min':min(lags),'median':statistics.median(lags),'max':max(lags)}},'by_panel_year':cov,'survivorship_warning':'NOT SURVIVORSHIP SAFE; source-level known limitation is 67/68 terminal entities lacking fundamentals; this panel match has zero terminal instruments with usable fundamentals.'}
 dump(O/'coverage_survivorship.json',coverage)
 decisions={'pit_market_cap':{'classification':'BLOCKERAD','reason':'number_Of_Shares is not verified period-end outstanding shares; price/share split bases cannot be matched; corporate-action effective dates and class-level share counts are incomplete','proxy':'price × latest reported number_Of_Shares is computable but must not be called market cap and is not approved for K2'},'pit_ev':{'classification':'BLOCKERAD','reason':'net_Debt is PIT-approved, but EV inherits blocked market cap denominator','approved_component':'net_Debt; do not reconstruct pseudo debt-minus-cash'},'value_within_momentum':{'classification':'FORTSATT BLOCKERAD','future_test_constraint':'Matched-population diagnostic only and NOT SURVIVORSHIP SAFE after a separate approved market-cap foundation'}}
 dump(O/'data_decisions.json',decisions)
 matrix=[]
 for name,num,den,ev in [('earnings_yield','profit_To_Equity_Holders','PIT market cap',False),('fcf_yield','free_Cash_Flow','PIT market cap',False),('sales_yield','revenues','PIT market cap',False),('book_to_market','total_Equity','PIT market cap',False),('dividend_yield','dividend per share','compatible unadjusted price',False),('ebitda_to_ev','EBITDA','PIT EV',True),('ebit_to_ev','operating_Income','PIT EV',True),('fcf_to_ev','free_Cash_Flow','PIT EV',True)]:matrix.append({'feature':name,'formula':f'{num} / {den}','numerator':num,'denominator':den,'market_known_time':'latest report_date <= panel_date; price strictly observed by panel decision time','units':'ratio','coverage_ceiling_rows':26907 if name!='fcf_yield' and name!='fcf_to_ev' else 26890,'missing_semantics':'NULL; never zero-impute','economic_issue':'financial companies require separate applicability rule for EV ratios' if ev else None,'pit_status':'BLOCKED_BY_DENOMINATOR'})
 dump(O/'value_feature_inventory.json',matrix)
 qa={'market_cap_constructed':False,'ev_constructed':False,'historical_market_cap_sanity_comparison_performed':False,'reason_sanity_not_performed':'A reconstruction with an unverified denominator would validate a proxy, not PIT market cap. Stopped before construction as preregistered forensic gate required.','price_decision':{'unadjusted_close':'actual traded price but incompatible with potentially restated/weighted share denominator','adjusted_close':'total-return adjusted, including dividends; economically invalid as market-cap price'},'general_multiclass_rule':'Exclude until company-level equity value can be built from class-level outstanding shares × class prices, including unlisted classes; never multiply total-company shares by each class or one arbitrary class.'}
 dump(O/'construction_gate_qa.json',qa)
 manifest={'version_id':'K2A_PIT_MARKET_CAP_EV_DATA_AUDIT_BLOCKED_V1_IMMUTABLE_2026-08-09','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'data QA only; no target, IC, alpha, ranking or backtest','inputs':[{'path':str(p.relative_to(R)),'bytes':p.stat().st_size,'sha256':sha(p)} for p in FILES],'outputs':[]}
 outs=sorted(p for p in O.iterdir() if p.is_file());manifest['outputs']=[{'path':str(p.relative_to(R)),'bytes':p.stat().st_size,'sha256':sha(p)} for p in outs];dump(O/'manifest.json',manifest);(O/'manifest.sha256').write_text(sha(O/'manifest.json')+'  manifest.json\n');print(json.dumps(decisions,ensure_ascii=False,indent=2))
if __name__=='__main__':main()
